name: Build and Tag .deb Package

on:
  push:
    branches:
      - main  # or whichever branch you are working on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git for Actions
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bash iputils-ping nmap openssl dnsutils

    - name: Build .deb package
      run: |
        mkdir -p debian/usr/local/bin
        cp pinghub.sh debian/usr/local/bin/pinghub
        chmod +x debian/usr/local/bin/pinghub
        dpkg-deb --build debian

    - name: Create and push tag
      run: |
        git tag -a v1.0.1 -m "Release v1.0.1"
        git push origin v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload .deb package artifact
      uses: actions/upload-artifact@v3
      with:
        name: pinghub-package
        path: debian.deb
