name: Build and Upload Debian Package

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev debhelper build-essential
      - name: Configure Git
        run: |
          git config --global user.name "hossein"
          git config --global user.email "hossein.masihi@gmail.com"

      - name: Build .deb package
        run: |
          mkdir -p pibghub/debian/usr/local/bin
          cp ./pinghub.sh pinghub/debian/usr/local/bin/pinghub  # Ensure correct path
          chmod +x pinghub/debian/usr/local/bin/pinghub
          dpkg-deb --build pinghub/debian

      - name: Tag release v1.0.1
        run: |
          git tag -a v1.0.1 -m "Release v1.0.1"
          git push origin v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pinghub-package
          path: debian.deb
