name: Build and Upload Debian Package

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev debhelper build-essential

      - name: Build .deb package
        run: |
          mkdir -p debian/usr/local/bin
          cp pinghub.sh debian/usr/local/bin/pinghub
          chmod +x debian/usr/local/bin/pinghub
          dpkg-deb --build debian

      - name: Tag release v1.0.1
        run: |
          git tag -a v1.0.1 -m "Release v1.0.1"
          git push origin v1.0.1

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pinghub-package
          path: debian.deb
